server:
  port: ${PORT:8082}

spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/catalog}
    username: ${DB_USER:booking}
    password: ${DB_PASSWORD:booking}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
